### ISSUE TITLE
smarter way to extend quickjump4ward

### ISSUE THREAD

**Issue by mediabakery** [psi-4ward/quickjump4ward#4]
Maybe, you know a smarter way to extend quickjump4ward. It's really easy to extend your extension, but it would be great when there is an easy way to extend the <strong>generateRequest</strong> method in quickjump4ward.js to add sections.

**Comment by psi-4ward** [comment]
see the **develope** branch 061cc17600621e371d80d5168ddb61e679d7ca26

you sould now be able to do something like 

``` javascript
Quickjump4ward.sections['mm']       = 'myModifier';
```

in you javascript file

**Comment by mediabakery** [comment]
thanks! I'll check it out this week.
