### ISSUE TITLE
Backend-Modul-Ansicht bleibt eingeklappt wenn alle geschlossen waren

### ISSUE THREAD

**Issue by Ainschy** [psi-4ward/quickjump4ward#6]
Hi Psi,

während einer Screencast Aufzeichnung für einen Kunden fiel mir folgendes im Zusammenhang mit der quickjump4ward Erweiterung auf.

Ich klappte alle Backend Module ein und anschließen die Inhalts Module auf um mit diesen zu starten. Als ich auf Artikel ging klappte die Inhalt-Module wieder ein. Ich habe dann einfach alle Backend-Module ausgeklappt und bin in System -> Einstellungen gegangen. Mit dem Aufruf von Einstellungen waren wieder alle Backend-Module eingeklappt.

Ich habe quickjump4ward dann erstmal deaktiviert um das Verhalten ohne das Modul noch einmal nachstellen zu können. Alles OK. Also quickjump wieder aktiviert und noch mal durchgespielt. Wieder der gleiche Fehler wenn ALLE Backend-Module einmal zugeklappt waren.

Alternativ habe ich unter den persönlichen Einstellungen die Temp Dateien gelöst und alle Backen-Module waren wieder offen.

Ich hoffe, das ich das Problem genau genug beschreiben konnte.

eingesetzte Erweiterungen:

Contao 2.11.5
Avisota 1.7.0.3
dropdown 1.0.0.23
syncCto 2.2.0.5
efg 1.16.0.27
glh_googlemaps 1.1.3.5
coverpicture 1.0.8.60

und den jeweils anhängigen Modulen

Gruß Oliver

**Comment by psi-4ward** [comment]
Ich kann den Fehler leider nicht nachstellen. Setzt du Quickjump4ward in der Version 1.4.1 ein?

**Comment by Ainschy** [comment]
Moin, ja ich hatte die 1.4.1 Build 3 eingesetzte, nach dem Update auf Build 5 war der Fehler verschwunden. Danke
