### ISSUE TITLE
feature request show root name

### ISSUE THREAD

**Issue by valentin-** [psi-4ward/quickjump4ward#8]
hi,

is it possible to add an option in settings, to add the root page of the current page (when using "p:" and "a:") to make it clearer if there are more pages with the same name?

![bildschirmfoto 2014-01-14 um 08 23 31](https://f.cloud.github.com/assets/90033/1908192/d5fc20f0-7cec-11e3-940f-079581942ed4.png)

what do you think?

**Comment by psi-4ward** [comment]
I see the problem but youre really think adding the root-page would solve the problem? Ive seen many websites having the same page-names under the same root. Perhaps we sould add the parent pagename if the name is ambigious

**Comment by valentin-** [comment]
you're right, i think to add the parent page would be the better solution.
